### ISSUE TITLE
Document all environment variables

### ISSUE THREAD

**Issue by Mte90** [cheshire-cat-ai/docs#33] opened 2023-03-27 14:32 UTC
Just a ticket to gather what is missing and need to be documented.

## Env variables

There isn't just only the openai key but also the path for the sqllite database https://github.com/pieroit/cheshire-cat/blob/main/web/cat/db/database.py#L6

## Documentation

* document somewhere that the project saves the chat exchanges in a sqlite database

**Comment by pieroit** [comment] 2023-09-26 16:54
Closing as duplicate of #28

**Closed by pieroit** 2023-09-26 16:54 UTC
